<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Whip_BasicMessage' => $baseDir . '/admin/includes/lib/whip/src/messages/Whip_BasicMessage.php',
    'Whip_Configuration' => $baseDir . '/admin/includes/lib/whip/src/Whip_Configuration.php',
    'Whip_DismissStorage' => $baseDir . '/admin/includes/lib/whip/src/interfaces/Whip_DismissStorage.php',
    'Whip_EmptyProperty' => $baseDir . '/admin/includes/lib/whip/src/exceptions/Whip_EmptyProperty.php',
    'Whip_Host' => $baseDir . '/admin/includes/lib/whip/src/Whip_Host.php',
    'Whip_HostMessage' => $baseDir . '/admin/includes/lib/whip/src/messages/Whip_HostMessage.php',
    'Whip_InvalidOperatorType' => $baseDir . '/admin/includes/lib/whip/src/exceptions/Whip_InvalidOperatorType.php',
    'Whip_InvalidType' => $baseDir . '/admin/includes/lib/whip/src/exceptions/Whip_InvalidType.php',
    'Whip_InvalidVersionComparisonString' => $baseDir . '/admin/includes/lib/whip/src/exceptions/Whip_InvalidVersionComparisonString.php',
    'Whip_InvalidVersionRequirementMessage' => $baseDir . '/admin/includes/lib/whip/src/messages/Whip_InvalidVersionRequirementMessage.php',
    'Whip_Listener' => $baseDir . '/admin/includes/lib/whip/src/interfaces/Whip_Listener.php',
    'Whip_Message' => $baseDir . '/admin/includes/lib/whip/src/interfaces/Whip_Message.php',
    'Whip_MessageDismisser' => $baseDir . '/admin/includes/lib/whip/src/Whip_MessageDismisser.php',
    'Whip_MessageFormatter' => $baseDir . '/admin/includes/lib/whip/src/Whip_MessageFormatter.php',
    'Whip_MessagePresenter' => $baseDir . '/admin/includes/lib/whip/src/interfaces/Whip_MessagePresenter.php',
    'Whip_MessagesManager' => $baseDir . '/admin/includes/lib/whip/src/Whip_MessagesManager.php',
    'Whip_NullMessage' => $baseDir . '/admin/includes/lib/whip/src/messages/Whip_NullMessage.php',
    'Whip_Requirement' => $baseDir . '/admin/includes/lib/whip/src/interfaces/Whip_Requirement.php',
    'Whip_RequirementsChecker' => $baseDir . '/admin/includes/lib/whip/src/Whip_RequirementsChecker.php',
    'Whip_UpgradePhpMessage' => $baseDir . '/admin/includes/lib/whip/src/messages/Whip_UpgradePhpMessage.php',
    'Whip_VersionDetector' => $baseDir . '/admin/includes/lib/whip/src/interfaces/Whip_VersionDetector.php',
    'Whip_VersionRequirement' => $baseDir . '/admin/includes/lib/whip/src/Whip_VersionRequirement.php',
    'Whip_WPDismissOption' => $baseDir . '/admin/includes/lib/whip/src/Whip_WPDismissOption.php',
    'Whip_WPMessageDismissListener' => $baseDir . '/admin/includes/lib/whip/src/Whip_WPMessageDismissListener.php',
    'Whip_WPMessagePresenter' => $baseDir . '/admin/includes/lib/whip/src/presenters/Whip_WPMessagePresenter.php',
    'Yoast_I18n_WordPressOrg_v3' => $baseDir . '/admin/includes/lib/i18n-module/src/i18n-module-wordpressorg.php',
    'Yoast_I18n_v3' => $baseDir . '/admin/includes/lib/i18n-module/src/i18n-module.php',
);
