<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'e7a23b473708f4b0fb5b99fe921bee83' => $baseDir . '/public/includes/lib/widgets-helper/wph-widget.php',
    '995b589e693a50f54393aa31ee1c3763' => $baseDir . '/admin/includes/lib/whip/src/facades/wordpress.php',
);
